# Generated by Django 4.2 on 2023-05-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
