# Generated by Django 4.2 on 2023-05-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_user_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.IntegerField(max_length=200),
        ),
    ]
