# Generated by Django 4.2 on 2023-05-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product_id',
        ),
    ]
