# Generated by Django 4.2 on 2023-05-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_products_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
