# Generated by Django 4.2 on 2023-05-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.BigIntegerField(max_length=200),
        ),
    ]
