# Generated by Django 4.2 on 2023-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.BigIntegerField(blank=True, max_length=200, null=True),
        ),
    ]
