# Generated by Django 4.2 on 2023-05-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_history_date_alter_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=10, max_length=200),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
