# Generated by Django 4.2 on 2023-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_history_price_alter_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
